### ISSUE TITLE
No sandboxing on Heroku

### ISSUE THREAD

**Issue by Matoo125** [sindresorhus/pageres#387] opened 2020-05-22 14:22 UTC
Hello,

After trying to run this app on Heroku, I became stuck on `No usable sandbox error`

```
[0522/134041.203033:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```

But if I look at [pupeteer documentation](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-heroku) specific to Heroku, there is written I should make sure sandboxing is turned off. 

> Ensure that you're using '--no-sandbox' mode when launching Puppeteer. This can be done by passing it as an argument to your .launch() call: puppeteer.launch({ args: ['--no-sandbox'] });.

And unfortunately **pageres** doesn't seem to have this opinion.

Does anyone knows how this can be resolved?

Thanks in advance. 

Matej

**Comment by sindresorhus** [comment] 2020-05-26 06:28
Duplicate of #365

**Comment by sindresorhus** [comment] 2020-05-26 06:28
That API would enable passing this flag.

**Closed by sindresorhus** 2020-05-26 06:28 UTC
