### ISSUE TITLE
Feature request:  enable ignore 404 - File not found

### ISSUE THREAD

**Issue by sstadelman** [sindresorhus/pageres#244] opened 2016-03-11 05:39 UTC
I'm working with an [openUI5](http://openui5.org) project in the SAP ecosystem, and it happens that UI5 is notorious for both the number of files used at runtime, and the number of 404 resource load failures which are expected to fail gracefully.  It would be great if there was an option `--ignore-errors` which allowed the image generation to complete, regardless of the state of the context.  

Here's an example of the error I'm seeing (only visible in the CLI -- seems to hang in pageres if delay is > 14-15, else completes without `'done'`):
```
$ pageres localhost:3003/SAPUI5Tutorials/webapp/index.html 375x677 --crop --scale=2 --delay=2 --verbose
failed to load 'sap/ui/demo/wt/Component-preload.js' from ./Component-preload.js: 404 - File not found
Caused by: undefined → http://localhost:3003/SAPUI5Tutorials/resources/sap-ui-core.js on line 88 in function f1
```
I see this 404 error in Chrome also, but there it is just logged and ignored.

-------------
Some additional details:  I dug into `pageres/dist/index.js`, and compared the runtime sequence of a successful execution (apple.com) vs. the error case.  I found that in `run()`, both cases correctly progress to `case 7`, after setting `context$2$0.next = 7` in `case 2`, *and* both correctly set `context$2$0.next = 9` in `case 7`.  But in the failure case, the switch evaluates `(context$2$0.prev = context$2$0.next)` as `'end'`, while in the success case it is evaluated to `9`.  

Oddly, in both cases, `context$2$0.next = 9`, and `context$2$0.prev = 7`.  

*Edit*:  Looks like there is probably a barf in the babel-runtime `AsyncIterator`...?

**Comment by sstadelman** [comment] 2016-03-11 06:00
In babel-runtime/regenerator/runtime.js Line 152 block:
```javascript
if (value instanceof AwaitArgument) {
          return _Promise.resolve(value.arg).then(function (value) {
            invoke("next", value, resolve, reject);
          }, function (err) {
          console.log('AwaitArgument Err:  ' + JSON.stringify(err, null, 2));
            invoke("throw", err, resolve, reject);
          });
        }
```
prints:
```
AwaitArgument Err:  {
  "noStack": true
}
```

**Comment by sindresorhus** [comment] 2016-03-11 18:19
> It would be great if there was an option --ignore-errors which allowed the image generation to complete, regardless of the state of the context.

No need for an option. That's the default. If not, it's a bug.

**Comment by SamVerschueren** [comment] 2016-03-11 18:24
I can test this locally but I need to understand the issue correctly :).

So the problem is that your page is including a script that results in a 404 because the script can't be found?

**Comment by davisshaver** [comment] 2016-05-10 15:51
I have a similar issue @sindresorhus @SamVerschueren.

Using the Shots package, I am seeing the following `pageres` error due to an on-page uncaught JS error. 

```
(env)➜  shots2 shots philly.com -c 1 -o ~/Desktop/shotsoutput/ --verbose
  shots dest directory set to: /Users/davis/Desktop/shotsoutput/ +0ms
  shots pmkdirp(pages) +3ms
  shots pmkdirp(screenshots) +1ms
  shots pmkdirp(diffs) +0ms
  shots pmkdirp(output) +0ms
  shots rglob('/Users/davis/Desktop/shotsoutput/pages/*.html') +5ms
  shots resolving download stage +0ms
  shots waybackpack philly.com -d /Users/davis/Desktop/shotsoutput/pages --start 20160507072940 +8s
  shots rglob('/Users/davis/Desktop/shotsoutput/pages/*.html') +8s
  shots rglob('/Users/davis/Desktop/shotsoutput/screenshots/*.html.png') +1ms
  shots resolving screenshots stage +0ms
  shots shot chunk(sources) and filter, len=11831 +4s
  shots shot chunk reducer, len=11830 +0ms
  shots reducing chunk 1/11830, len=1 +11ms
  shots creating pageres instance +0ms
  shots adding pageres src /Users/davis/Desktop/shotsoutput/pages/philly-com-20160507070636.html, sizes=1024x768 +0ms
  shots ERR! Error: /web/20160507070754/http://requirejs.org/docs/errors.html#scripterror → https://web.archive.org/web/20160507070754js_/http://launch.newsinc.com/132/js/embed.js on line 69 in function defaultOnError +6s
{ [Error: /web/20160507070754/http://requirejs.org/docs/errors.html#scripterror → https://web.archive.org/web/20160507070754js_/http://launch.newsinc.com/132/js/embed.js on line 69 in function defaultOnError] noStack: true }
```

is there a recommended media to ignore or skip pages with JS error gracefully?

**Comment by SamVerschueren** [comment] 2016-05-10 17:15
I'll have a look if it's possible to ignore those errors. Apparently lots of sites are having crappy scripts which breaks our library.

**Comment by davisshaver** [comment] 2016-05-10 18:09
@samverschueren That is exactly the case :). But maybe even crappy sites deserve to be remembered/screenshotted?

If I can help please let me know. I had thought that you were using PhantomJS as it's in the package.json but I didn't see it used in pageres, perhaps you could point me to that as I think we should be able to give PhantomJS a nulled out `onError` as outlined here http://phantomjs.org/api/phantom/handler/on-error.html

**Comment by SamVerschueren** [comment] 2016-05-10 18:13
We are using [screenshot-stream](https://github.com/kevva/screenshot-stream) which is a nice interface to PhantomJS.

**Comment by SamVerschueren** [comment] 2016-05-12 18:55
This bug should be fixed in `screenshot-stream`. You have to reinstall `pageres` so it installs the latest `screenshot-stream` version and then try it again. I'll close this issue for now. If it's still not resolved, let us know.

**Closed by SamVerschueren** 2016-05-12 18:55 UTC
Labels: bug, help wanted
