### ISSUE TITLE
WebFonts not rendering yet

### ISSUE THREAD

**Issue by steoo** [sindresorhus/pageres#174] opened 2015-05-02 18:32 UTC
I have already followed the other issues ( e.g. https://github.com/sindresorhus/pageres/issues/152 ) but both `API` and `cli` are not rendering webfonts, both widh `font-face` and `link` inclusion. 
I have not phantomjs installed globally, I re-installed multiple times pageres and made sure it was the right version. 
Any thought?

**Comment by sindresorhus** [comment] 2015-05-02 20:11
Try running with the verbose flag and share the output: `pageres --verbose`.

Would also be useful if you could share a test-case or URL that reproduces it ;)

**Comment by steoo** [comment] 2015-05-02 20:14
I tried also with yeoman.Io to understand if it was my own script related
problem and it didn't work either. (There is a Roboto Sans heading)
Il 02/mag/2015 22:11, "Sindre Sorhus" <notifications@github.com> ha scritto:

**Comment by sindresorhus** [comment] 2015-05-02 20:45
Hmm, yeah, I can reproduce. Weird, it used to work.

**Comment by derhuerst** [comment] 2015-05-18 21:08
any news about this? with v1.3.0 it still didn't work.

**Comment by kevva** [comment] 2015-05-19 09:38
This is weird.

**Comment by steoo** [comment] 2015-05-19 10:55
Yes, It used to work couple month ago, I guess it did not change a lot in the meantime.

**Comment by crstauf** [comment] 2015-06-06 16:09
any progress on this? screenshots without webfonts is a no-go.

**Comment by kevva** [comment] 2015-06-06 16:10
We're still waiting for PhantomJS 2.0.

**Comment by derhuerst** [comment] 2015-06-13 03:00
@kevva 

> We're still waiting for PhantomJS 2.0.

What does "waiting" mean?

**Comment by blackrosezy** [comment] 2015-06-14 17:53
@derhuerst  Probably the issue is fixed in phantom-js 2.0 .Currently the latest stable release for phantom-js is `1.9.7`(https://github.com/ariya/phantomjs/releases)

**Comment by pablodenadai** [comment] 2015-06-20 22:45
Looks like PhantomJS 2 is already released as stable. From their official GitHub page: "The latest stable release is version 2.0.".

**Comment by zmwangx** [comment] 2015-06-20 22:50
@pablodenadai The source and tag is there, but the latest version on [https://www.npmjs.com/package/phantomjs](npm) is 1.9.17. The problem seems to be OS X and Linux binary builds. See https://github.com/Medium/phantomjs/issues/288#issuecomment-73424312.

**Comment by kevva** [comment] 2015-06-20 22:50
@pablodenadai, yeah, but there aren't any precompiled binaries for Linux still. See https://github.com/ariya/phantomjs/issues/12948.

**Comment by sindresorhus** [comment] 2015-06-20 22:52
Keep 2.0 discussion to https://github.com/sindresorhus/pageres/issues/77

But in short; the PhantomJS 2.0 release was completely borked and should never have been released. We're still waiting on precompiled 2.0 binaries for Linux and then we have to wait for https://github.com/Medium/phantomjs to update.

**Comment by oliverbenns** [comment] 2015-08-11 00:38
Any news with this? This is quite the deal breaker.

**Comment by quanghoc** [comment] 2015-10-11 22:51
+1

**Comment by kevva** [comment] 2015-10-12 07:06
No need for bumping this. This will be fixed as soon as PhantomJS 2.0 works in Linux.

**Comment by julmot** [comment] 2015-11-15 11:03
:+1: I'm bumping this because I want to get informed if it is fixed. I would love to integrate this task into [jmBoilerplate](https://github.com/julmot/jmBoilerplate).

**Comment by SamVerschueren** [comment] 2015-11-29 18:21
Sorry, still no PhantomJS 2

**Comment by brunowego** [comment] 2016-01-11 16:34
+1

**Comment by oliverbenns** [comment] 2016-01-11 22:22
This problem has stopped people using this tool for 9 months, making it pretty redundant. Excuse my lack of knowledge, but can we not just revert to an older version of PhantomJs?

**Closed** 2016-01-26 20:35 UTC
