### ISSUE TITLE
Setting a Default Background color if transparent

### ISSUE THREAD

**Issue by dlbrown06** [sindresorhus/pageres#208] opened 2015-09-21 10:33 UTC
When snapping webpages that have a transparent image, the image is snapped with the white and grey boxes indicating transparency. It would be nice to maybe detect that and default the background to white or something.

Just a enhancement suggestion. I don't think there is really anything I could do to get around that at this point.

**Comment by sindresorhus** [comment] 2015-09-21 10:44
We already do that. Might be a duplicate of https://github.com/sindresorhus/pageres/issues/192.

**Comment by dlbrown06** [comment] 2015-09-22 10:12
The resolution is to set the delay then? I set it to 20 seconds and no dice.

**Comment by kevva** [comment] 2015-10-02 11:55
Do you have an example URL we could test?

**Comment by SamVerschueren** [comment] 2015-11-28 20:36
@dlbrown06 ping

**Comment by SamVerschueren** [comment] 2015-12-04 08:16
Closing this due to inactivity. Please reopen with more information.

**Closed by SamVerschueren** 2015-12-04 08:16 UTC
