### ISSUE TITLE
Allow other formats other than PNG

### ISSUE THREAD

**Issue by mugendi** [sindresorhus/pageres#162] opened 2015-02-15 03:50 UTC
PNG is great for vector graphics but not always the best for raster graphics.I have a project that required JPEG image captures and had to edit /lib/util.js to allow for dynamic image format settings rather than the hard-coded PNG format.

It would be nice to allow for that flexibility and all that's needed is an edit on line 141 to:
var filename = _.template(options.filename + **'.'+options.format**, {

**Comment by kevva** [comment] 2015-02-15 12:29
Duplicate of https://github.com/sindresorhus/pageres/issues/129. Use `--format jpeg` if you're using the CLI or `format: 'jpeg'` if you're using the API directly.

**Closed by kevva** 2015-02-15 12:29 UTC

**Comment by sindresorhus** [comment] 2015-02-16 02:37
@kevva Maybe we should document it?

**Comment by kevva** [comment] 2015-02-16 07:20
Probably.

**Comment by kevva** [comment] 2015-02-16 17:51
@sindresorhus, I've added a fix for accepting `jpg` as format. Could you fix the documentation here :)))?

**Comment by sindresorhus** [comment] 2015-02-16 18:16
Done in https://github.com/sindresorhus/pageres/commit/0f32f7e8152dd32448b6e1db8b3131a1c6ee6371

**Comment by mugendi** [comment] 2015-02-19 17:21
@sindresorhus @kevva thanks guys!
