### ISSUE TITLE
Crash on absolute local path

### ISSUE THREAD

**Issue by nicolas-raoul** [sindresorhus/pageres#206] opened 2015-09-11 07:03 UTC
```
$ pageres /tmp/frameset.html 800x800
/usr/local/lib/node_modules/pageres-cli/cli.js:102
                                throw err;
                                      ^
TypeError: Cannot call method 'split' of null
    at mapDomain (punycode.js:89:21)
    at Object.toUnicode (punycode.js:441:10)
    at module.exports (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/filenamify-url/node_modules/humanize-url/node_modules/normalize-url/index.js:57:29)
    at module.exports (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/filenamify-url/node_modules/humanize-url/index.js:10:9)
    at module.exports (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/filenamify-url/index.js:10:20)
    at Pageres.exports.create (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/util.js:158:8)
    at Pageres.<anonymous> (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/index.js:113:26)
    at Array.forEach (native)
    at Pageres.eachAsync.stats.urls (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/index.js:109:9)
    at Object.immediate._onImmediate (timers.js:348:16)
```

```
$ cat /tmp/frameset.html 
<frameset rows="100%">
  <frameset cols="100%">
    <frame src="https://tools.wmflabs.org/wikivoyage/w/poimap2.php?lat=126.9836&lon=37.5814&zoom=13&lang=en&name=Seoul/Jongno" frameborder="0" scrolling="no">
  </frameset>
</frameset>
```

```
$ pageres --version
1.1.1
```

Ubuntu 2015.04

**Comment by nicolas-raoul** [comment] 2015-09-11 07:21
Workaround:
```
cd /tmp
pageres frameset.html 800x800
```
pageres-cli does not seem to work with absolute local paths.

**Comment by sindresorhus** [comment] 2015-09-11 07:22
Yup, can reproduce.

**Comment by nicolas-raoul** [comment] 2015-09-11 08:15
Similar bug for the value of `--filename`:
```
$ frameset.html 800x800 --filename /tmp/screenshot.png

/usr/local/lib/node_modules/pageres-cli/cli.js:102
                                throw err;
                                      ^
Error: ENOENT, open '/tmp/tmp/screenshot.png.png.8e72b57124e7cbe4ff7f1869d53ffd8a'
```
Should I file another issue?
Cheers!

**Comment by sindresorhus** [comment] 2015-09-11 08:22
@nicolas-raoul `/tmp/screenshot.png` is an invalid filename. What you specified there is a filepath. Please read the docs about the `filename` option.

**Comment by nicolas-raoul** [comment] 2015-09-11 08:24
Oh I see, thanks!

**Comment by SamVerschueren** [comment] 2015-11-29 18:25
Cannot reproduce. Might be fixed in the latest version. Can you upgrade and test again?

**Comment by nicolas-raoul** [comment] 2015-11-30 04:54
Bug still present:
```
$ pageres --version
2.0.0
$ pageres /tmp/frameset.html 800x800
TypeError: Cannot call method 'split' of null
    at mapDomain (punycode.js:89:21)
    at Object.toUnicode (punycode.js:441:10)
    at module.exports (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/filenamify-url/node_modules/humanize-url/node_modules/normalize-url/index.js:57:29)
    at module.exports (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/filenamify-url/node_modules/humanize-url/index.js:10:9)
    at module.exports (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/filenamify-url/index.js:10:20)
    at Pageres.create (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/util.js:388:39)
    at /usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:137:33
    at Array.map (native)
    at Pageres.run$ (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:109:64)
    at tryCatch (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/babel-runtime/regenerator/runtime.js:72:40)
```

**Comment by SamVerschueren** [comment] 2015-11-30 07:08
My bad, can reproduce. Will have a look at it later today.

**Closed** 2015-11-30 09:23 UTC
Labels: bug, help wanted

**Comment by nicolas-raoul** [comment] 2015-12-11 14:48
Bug still present in 3.0.2:
```
$ pageres /tmp/frameset.html 800x800 --filename screenshot
TypeError: Cannot call method 'split' of null
    at mapDomain (punycode.js:89:21)
    at Object.toUnicode (punycode.js:441:10)
    at module.exports (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/filenamify-url/node_modules/humanize-url/node_modules/normalize-url/index.js:57:29)
    at module.exports (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/filenamify-url/node_modules/humanize-url/index.js:10:9)
    at module.exports (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/filenamify-url/index.js:10:20)
    at Pageres.create (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/util.js:388:39)
    at /usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:137:33
    at Array.map (native)
    at Pageres.run$ (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:109:64)
    at tryCatch (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/babel-runtime/regenerator/runtime.js:72:40)
```
```
$ npm list -g pageres
/usr/local/lib
├── pageres@3.0.2 
└─┬ pageres-cli@2.0.0
  └── pageres@3.0.2 
$ npm list pageres
/home/nico
└── pageres@3.0.2
```

**Comment by nicolas-raoul** [comment] 2015-12-11 16:05
Upgrading to NodeJS 5.2.0 fixed the problem! :-)
