### ISSUE TITLE
Heroku CLI

### ISSUE THREAD

**Issue by m8rzel** [sindresorhus/pageres#422] opened 2021-11-23 09:13 UTC
Hey,
we are working with your create npm package. 
Local it works fine but on our heroku server, the file does not download

![Bildschirmfoto 2021-11-23 um 10 12 49](https://user-images.githubusercontent.com/40661691/142997544-4a237a18-32f5-42da-bc80-e925e1cabe93.png)

do you have any ideas?
thanks a lot
Marcel

**Comment by sindresorhus** [comment] 2021-11-23 09:27
Look at the Heroku logs. Either the install did not properly download Puppeteer or you exceeded some memory limit in Heroku. I'm going to close this as it's unlikely it is an issue with this package specifically.

I'm happy to look further into this if you submit a failing test that proves the problem is Pageres.

**Closed by sindresorhus** 2021-11-23 09:27 UTC
